### ISSUE TITLE
Chinese & Japanese的模型无法生成音频

### ISSUE THREAD

**Issue by Hatanezumi** [CjangCjengh/TTSModels#1]
Chinese & Japanese的模型无法生成中文和日文音频，但英文可以。

**Comment by soloopooo** [comment]
请参照 `text\cleaners.py: zh_ja_mixture_cleaners()` 函数，在中文字符串两侧添加`[ZH]`，日文添加`[JA]`

**Comment by Hatanezumi** [comment]
好的，问题已经解决

**Comment by Hatanezumi** [comment]
好的，问题已经解决
